[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NPM_USE_PRODUCTION_BUILD = "true"
  SECRETS_SCAN_OMIT_KEYS = "STORYBLOK_PREVIEW_TOKEN"

# Redirect all requests to Next.js for client-side routing
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  conditions = {Role = ["admin"]}

# Handle Next.js dynamic routes
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

# API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Catch all for Next.js pages
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, immutable, max-age=31536000"

# Cache images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Preview deploys configuration
[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"

# Production environment variables will be set in Netlify dashboard

# Secrets scanning configuration - allow Storyblok token in build output